'use strict';

promise.then(f1).catch(f2); // catch поймает и обработает ошибку

promise.then(f1, f2);
